[IV-22-23] Objetivo 0
lovelace9981/IV pull request #2
Opened 2022-09-14 22:38 UTC by lovelace9981

* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
Sí, es un problema que muchas empresas no conocen o suelen resolverlo de manera "manual". Tengo experiencia personal, ya que en la recepción de las devoluciones, no se conoce a quién debe ir una devolución en concreto, no se conoce si un técnico está muy ocupado o poco ocupado.
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue  de una aplicación en la nube?
Sí, la aplicación en la nube permite a la empresa de compra online descentralizar la lógica que permite automatizar las asignaciones de los productos devuelto a cada técnico especializado, proceso que se suele realizar manualmente.
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
Sí, hay una asignación de balanceo de carga al técnico especializado en el producto devuelto menos ocupado.
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?
Sí.

2022-09-15 15:39 UTC, JJ requested changes
Deberías ser un poco más concreto, y resumir en una o dos frases
1. ¿Cuál es el problema que quieres resolver? Es decir, ¿qué tendrías que entregarle al cliente y qué tendría que hacer para que se considerara resuelto?
2. ¿Quién es el cliente? ¿Qué tipo de empresa? ¿Qué hace? ¿De qué tamaño? ¿Quién dentro de la empresa se a va a encargar de qué?
3. ¿Qué lógica de negocio, cómo vas a aportar valor?

Si pones excesivo detalle, no dejas mucho margen a la resolución del problema específico. Pero lo principal es que no se entiende realmetne qué vas a hacer.

2022-09-15 15:39 UTC, JJ commented on LICENSE
> +		       Version 2, June 1991
No sé muy bien por qué has cambiado la licencia a una verisón anterior. No es obstáculo para el objetivo, pero no lo entiendo.

2022-09-15 15:39 UTC, JJ commented on README.md
> +5. La empresa también necesita poder vender de nuevo un producto al cliente. Se puede clasificar y categorizar según la demanda de producto que tenga. Por ejemplo: La empresa vende muchos aires acond
De esto no tengo muy claro ni cuál es el problema, ni cuál es el cliente (¿de qué tipo de empresa estamos hablando? ¿Una aceitera? ¿Una compañía telefónica?), ni realmente cuál es la lógica de negocio.

2022-09-16 08:36 UTC, lovelace9981 commented on README.md
> +5. La empresa también necesita poder vender de nuevo un producto al cliente. Se puede clasificar y categorizar según la demanda de producto que tenga. Por ejemplo: La empresa vende muchos aires acond
@JJ Está listo para revisión espero ser mas claro y conciso.

2022-09-16 11:30 UTC, JJ approved these changes
Sigues sin identificar claramente un problema, un cliente y por qué necesita una solución tipo cloud.

2022-09-16 11:30 UTC, JJ commented on LICENSE
> +		       Version 2, June 1991
Sigo viendo raro este downgrade de la licencia. ¿Por qué no dejas la original?

2022-09-16 11:30 UTC, JJ commented on README.md
> +    <li>El cliente tiene una media de gasto alta/baja</li>
¿Qué problema hay? ¿Que los clientes que gastan más quieren colarse al principio de la cola y competir con los clientes que gastan menos teniendo el stock antes y evitando roturas de stock? 
Es decir, ¿vas a ayudar a los sucios capitalistas a que acaben con la competencia?

2022-09-16 11:30 UTC, JJ commented on README.md
> +    <li>El cliente hace compras recurrentes del pedido del mismo tipo en un periodo a elegir por la empresa que utilice el software.</li>
Una vez más, estás suponiendo soluciones a problemas que no están claramente establecidos. ¿Los clientes que hacen compras recurrentes quiere que los sirvan antes? Si lo hacen, ¿para qué hacen compras recurrentes?

2022-09-16 11:30 UTC, JJ commented on README.md
> +</ul>
Recuerda lo imprescindible en una metodología: Qué hago ahora, si lo que hago está bien o no. Tú puedes poner todas estas reglas (pero habrá que ver cómo las integras). Cuando lo hayas hecho, ¿qué problema has resuelto? ¿El de un 1% de los clientes que estaba insatisfecho? ¿Qué pasa con el resto de los clientes?

2022-09-16 11:30 UTC, JJ commented on README.md
> +Para resolver este objetivo el cliente necesita un sistema de prioridad que les ayude a clasificar las peticiones y reaccionar más apropiadamente con sus clientes.
Si no estableces el problema y formulas el problema como la solución, no puedes nunca saber si lo has solucionado. Estableces un sistema de prioridades, *cualquiera*. Problema resuelto, ¿no? No, porque no sabes realmente cuál es el problema. Los clientes pueden seguir insatisfechos, o los que lo estban lo estarán más, y los que estaban satisfecho lo estarán menos. Por eso si no tienes claro cuál es el problema, es imposible proceder con una forma de resolverlo.

2022-09-16 11:30 UTC, JJ commented on README.md
> +Las empresas suelen tener problemas a la hora de evaluar si un producto está siendo rentable, ya que los precios de los proveedores fluctúan. La empresa tiene un precio de venta a sus cliente y un po
Esto no tiene nada que ver con el anterior. El que lo envíes antes o después no tiene nada que ver con el beneficio de un producto. Y en todo caso, sigue sin ser un problema. ¿Qué resuelves visualizando el margen de beneficio? ¿Filtrando los datos (y qué datos)?

2022-09-16 11:30 UTC, JJ commented on README.md
> +### Lenguaje y licencia utilizado para llevar a cabo el proyecto
Esto no tienes que decirlo, ni se ha pedido.

2022-09-17 09:02 UTC, lovelace9981 commented
@JJ He subido una propuesta.

2022-09-17 09:35 UTC, JJ requested changes
Lo siento, Pedro, pero seguimos con el mismo problema
1. Has cambiado la licencia sin tener una buena razón. Ya te lo he señalado dos veces.
2. No formulas claramente *el* problema que quieres resolver o *el beneficio* que se va a obtener si se resuele el problema. Es decir, no está claro que calcular los beneficios que da un producto específico no sea trivial, ni que eso realmente sea un problema. En la fase de "empatizar" eso es lo que se espera hacer. Entender qué es lo que ocurre en un contexto determinado.
3. Tampoco está clara la lógica de negocio. Precio de venta - precio de compra = beneficios, ¿no? ¿Qué lógica de negocio más complicada hay?
4. No está claro qué puede hacerse en este programa que no se pueda hacer con uno de sobremesa. El ordenador que hace las ventas tiene información sobre inventario y la venta, ¿no?

Me da la impresión de que estás dando muchas vueltas a lo mismo, y en un entorno donde te resulta difícil empatizar con las personas que están ahí. Intenta pensar en portales de datos abiertos y qué beneficio podría obtener la población con ellos; por ejemplo este https://www.granada.org/inet/wambiente.nsf/opendata.htm (pero hay muchos más, también en la UGR)

2022-09-17 10:37 UTC, lovelace9981 commented
@JJ Licencia restaurada a la versión anterior y otra propuesta.

2022-09-17 16:40 UTC, JJ requested changes
De veras que me da apuro, Pedro, pero ¿eres consciente que esto tienes que programarlo dentro de la asignatura? ¿De veras que una plataforma cloud es mejor para esto que simplemente tener las herramientas en local? ¿Una serie de herramientas que son software libre? ¿Qué lógica de negocio habría aquí, aparte de compilar y medir... no tengo claro qué? Te digo lo mismo que con la propuesta relacionada con el escalado automático: hay herramientas que lo hacen, y lo hacen localmente.
Aparte que tampoco tienes claro ni el problema ni el cliente. Tienes que imaginar que el cliente dice algo así como "Ojalá alguien pudiera solucionar mi problema con la compilación de... algo". ¿Tú crees que hay de verdad alguien que dice eso?
Te vuelve a fallar la fase de empatía. Estás empezando por lo que quieres hacer, y luego pensando en clientes. Tienes que pensar en clientes, empatizar, y formular los problemas que pueden tener. Te agradezco el esfuerzo, y todas son ideas excelentes para una aplicación, TFG por ejemplo... Pero en la asignatura tenemos que partir de otras bases para poder realizar todas las fases correctamente.

2022-09-17 16:41 UTC, JJ commented
Te aconsejo también que pases cada vez que sugieras una idea la "lista de comprobación" que hay en el cuerpo; esta vez no la has actualizado. Y piensa bien las respuestas, por favor.

2022-09-20 17:04 UTC, lovelace9981 commented
Invernaderos agrícolas en la nube.

* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
Sí, es un problema que hace que de no resolverse se desperdician muchos recursos naturales o se pierdan cosechas por una pequeña desviación de un parámetro como un riego menor mayor temperatura, etc...
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue  de una aplicación en la nube?
Sí, la aplicación en la nube permite a la empresa o en su defecto el encargado de un invernadero conocer mejor el rendimiento de la cosecha por recursos utilizados y según el estado en el que se haya encontrado los invernaderos.
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
Sí, de hecho es necesario la obtención de los datos y procesado para obtener estadísticas que permitan analizar a la empresa el estado del rendimiento actual o pasado.
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?
Sí.


@JJ

2022-09-20 18:12 UTC, JJ requested changes
Pedro, este no es un ejercicio que entregas y a continuación olvidas. Es la base para el proyecto que vas a hacer a lo largo de la asignatura. En el siguiente objetivo se trata de hacer las historias de usuario, que es qué beneficio obtienen los usuarios. Lo único que se puede sacar de aquí es "como agricultor, quiero saber la media y la desviación típica del *estado* de mi invernadero".
En el 2 hay que programar estructuras de datos (posiblemente otra persona). ¿Vas a tener un array que se llame estados? En el 3 hay que testear la lógica de negocio. ¿Calculas la media del "estado" y si la media es, bueno, la media, entonces has resuelto el problema?
De verdad, tratad de enfocar esta asignatura, y este proyecto que estás planteando, con cierta perspectiva, la perspectiva de la ingeniería.

2022-09-20 18:12 UTC, JJ commented on README.md
> +La empresa o en su defecto el encargado, no tiene información directa del estado de sus invernaderos, de los recursos utilizados en este y tampoco tienen la información necesaria que les ayude a dete
¿Para resolver qué problema necesita tener información del estado de los invernaderos?
¿Qué es una cosecha con garantías? ¿Qué tiene que entregar el programa usando qué para que se pueda establecer que inequívocamente tiene esas garantías? ¿Son problemas diferentes o son el mismo problema?

2022-09-20 18:12 UTC, JJ commented on README.md
> +La nube es necesaria para tener un punto de reunión de datos que son vitales para la empresa como son, estados de los invernaderos recolectados con sensores de medición, los recursos utilizados por i
Pedro, tienes que implementar esto dentro de la asignatura. Y tienes que testear toda la lógica de negocio (que no tengo claro cuál es) usando datos lo más reales posibles. Si vas a testear una lógica con una serie de sensores, tendrás que simular esos sensores, y te va a costar tanto trabajo la simulación como la programación de la lógica de negocio (que, insisto, no sé cuál es ni de qué forma resuelve el problema)
Por definición, no se puede calcular media de "estados". Sólo se puede calcular de una variable continua.
Desviación típica y media son no triviales, pero no sé si contribuyen o no a resolver el problema, porque no sé cuál es el problema. Si es problema es saber la media y la desviación típica (¿con qué frecuencia? ¿Cada cuanto se consulta? ¿Quién es el cliente? ¿Un propietario de un invernadero va a saber qué es la media y la desviación típica?) tendrás que hacer, posiblemetne de forma explícita, la fase de "empatización", que entiende qué es el cliente y qué necesidades tiene.

2022-09-20 18:12 UTC, JJ commented on README.md
> +Los encargados de invernaderos de la empresa, pueden a partir de los datos recolectados y generados en la nube mejorar el rendimiento de las cosechas. También podrán experimentar y demostrar empírica
La lógica de negocio es lo que va a hacer el programa, no lo que va a hacer el cliente.

2022-09-20 18:17 UTC, lovelace9981 commented on README.md
> +La empresa o en su defecto el encargado, no tiene información directa del estado de sus invernaderos, de los recursos utilizados en este y tampoco tienen la información necesaria que les ayude a dete
Hola profesor, es el mismo problema. Porque, llamo como estados a la cantidad de agua utilizada en el regadío, temperatura ambiental, humedad del aire,... Entonces si hay una variación muy grande, como por ejemplo, se detecta que se está usando más litros de los habituales la cosecha se echa a perder.

2022-09-20 18:26 UTC, JJ commented on README.md
> +La empresa o en su defecto el encargado, no tiene información directa del estado de sus invernaderos, de los recursos utilizados en este y tampoco tienen la información necesaria que les ayude a dete
> Hola profesor, es el mismo problema. Porque, llamo como estados a la cantidad de agua utilizada en el regadío, temperatura ambiental, humedad del aire,... Entonces si hay una variación muy grande, como por ejemplo, se detecta que se está usando más litros de los habituales la cosecha se echa a perder.

Te digo lo mismo que más abajo. Para empezar, esas situaciones pueden ser o muy simples ("mucha agua" == agua > x) o muy compleja (hacer un análisis del estado del agua y ver si está creciendo de no sé qué forma, usando un sistema d emachine learning). No veo un estado intermedio que se pueda usar en la asignatura.
Y por otro lado, sigues teniendo el problema de los datos. Salvo que tengas datos reales de invernaderos reales y puedas probar los algoritmos que crees (machine learning o como sea) para comprobar si funcionan, todo se queda en una serie de tests académicos extremadamente simples.

Esta es también información nueva que no has mencionado antes. La información que tengas para poder evaluar, deberías ponerla en el PR.

2022-09-20 18:28 UTC, lovelace9981 commented on README.md
> +La nube es necesaria para tener un punto de reunión de datos que son vitales para la empresa como son, estados de los invernaderos recolectados con sensores de medición, los recursos utilizados por i
Hola profesor, los estados son los datos mencionados arriba en mi otro comentario, cantidad de agua utilizada, cantidad de compost, cantidad de pesticida, cualquier dato que sea relevante para que la cosecha salga con el máximo rendimiento posible, con el menor coste de recursos económicos y materiales. Por lo tanto es adaptable a cualquier empresa, si una empresa utiliza otro material/recurso que quieran trazar y hacer un seguimiento para ver si empeora o mejora la cosecha, pues se obtiene dicho registro.

Entonces la lógica de negocio sale a partir de esos datos, se extraen unos datos estadísticos que le indiquen qué mejoras se hacen en otros invernaderos, que están lejanos físicamente entre sí (ej. Invernadero en Huelva y Almería) y que el encargado del invernadero que no tenga dicha mejora, pueda ver esos datos sin tener que hablarlo con otro encargado de la misma empresa o ir físicamente a ese invernadero.

La frecuencia con la que se genera ese procesamiento es la misma con la que se introducen los datos de los estados, porque los recursos utilizados en las cosechas de los invernaderos tienden a ser estables, pero a veces hay ciertos valores que cambian que se pueden visualizar con el resumen  estadístico y mejorar la propia cosecha. O detectar qué ha cambiado en el caso de que haya empeorado.

El cliente son las empresas/cooperativas de invernaderos que disponen esta aplicación para apoyar a sus encargados de los invernaderos a mejorar todo lo posible en las cosechas con unos datos y resúmenes estadísticos que les ayude a buscar un punto "óptimo" para obtener sus cosechas.

Así como, los propios encargados pueden obtener la información filtrada de su propio invernadero para ver en qué estado se encuenta.

2022-09-20 18:38 UTC, JJ commented on README.md
> +La nube es necesaria para tener un punto de reunión de datos que son vitales para la empresa como son, estados de los invernaderos recolectados con sensores de medición, los recursos utilizados por i
Pablo, te compro que efectivamente haya un problema, aunque no lo estás formulando correctamente. El problema es que ciertas combinaciones de lecturas de sensores echan a perder la cosecha, o dan menos rendimiento, o algo así.
El problema es... el resto. La lógica de negocio para predecir... algo (¿rendimiento? ¿pérdida de la cosecha?) es tremendamente complicada, porque no tienes un modelo claro del problema (ya te digo que ni los agricultores lo tienen). Los datos. Los tests de que efectivamente la lógica de negocio programada funcione. En general, todo.
En general, va a pasar lo mismo que para cualquier sistema físico del que no tengas datos. Y si los tuvieras, seguirías teniendo el problema de entrenar el sistema de predición (con código propio, ojo) y validar los resultados.
Por favor, entended que no es juzgar el problema en sí. Pero entended también que esto es algo *que vais a programar* *durante esta asignatura*. No te estoy pidiendo el planteamiento de una tesis doctoral.

2022-09-20 18:46 UTC, lovelace9981 commented on README.md
> +La empresa o en su defecto el encargado, no tiene información directa del estado de sus invernaderos, de los recursos utilizados en este y tampoco tienen la información necesaria que les ayude a dete
Hola profesor, sí no la he puesto porque no quería extender el PR con información adicional que casi haga llegar a la solución. Si quiere puedo incluir la información que me indique en el PR hasta que esté válido.

Sobre el problema de los datos, los parámetros son introducidos por los encargados de los invernaderos: 

- Litros de agua usados para regar con una frecuencia. Ejemplo: Litros por día.
- Kilógramos de estiércol/copost utilizados.
- Temperatura del invernadero.
- Rendimiento de cosecha, esto es toneladas del producto plantado.
- Cualquier otro dato relevante para otra empresa de invernaderos...

Entonces si la empresa tiene una cantidad de 10, 20, 30 invernaderos, quiere obtener el resumen estadístico mediante la nube, o sea media de los datos de arriba para optimizar los invernaderos que han tenido peor rendimiento de cosecha o filtrar por orden de menor a mayor uso de litros de agua si ciertos invernaderos han obtenido mejor o peor cosecha.

2022-09-20 18:51 UTC, JJ commented on README.md
> +La empresa o en su defecto el encargado, no tiene información directa del estado de sus invernaderos, de los recursos utilizados en este y tampoco tienen la información necesaria que les ayude a dete
Creo que no me estás entendiendo tú a mi. Aunque tuvieras clara la lógica de negocio, es decir, las operaciones que vas a hacer con todos estos datos (y que *tú tendrás que programar*) no tienes esos datos. Y si los tuvieras, ya te he dicho que no parece nada fácil hacer predicciones con tantos factores.
Por favor, vuelve a la fase de "empatizar" y busca un problema que se pueda resolver con una lógica de negocio programable sin mucho esfuerzo y que valide las soluciones al problemas que vas a proponer desde tu aplicación.

2022-09-20 18:58 UTC, lovelace9981 commented on README.md
> +La empresa o en su defecto el encargado, no tiene información directa del estado de sus invernaderos, de los recursos utilizados en este y tampoco tienen la información necesaria que les ayude a dete
Hola profesor, no intento predecir la cosecha o buscar un modelo de predicción con machine learning. Lo que busco con mi lógica de negocio es algo mas sencillo, es simplemente que las empresas de invernaderos obtengan filtros de visualización por invernadero, filtrado por la cantidad de uso de un recurso, resúmenes estadísticos de los usos de los recursos. Todo ello para controlar que todo vaya adecuadamente y que sepan qué rendimiento de cosecha obtienen con esos recursos.

Entonces la empresa o sus encargados pueden reducir el desperdicio de los recursos controlando la cantidad utilizada y pudiendo ver si en otros invernaderos se obtiene mejor rendimiento en comparación al suyo.

2022-09-20 19:02 UTC, JJ commented on README.md
> +La empresa o en su defecto el encargado, no tiene información directa del estado de sus invernaderos, de los recursos utilizados en este y tampoco tienen la información necesaria que les ayude a dete
Creo que no me estás entendiendo tú a mi una vez más. Una lógica "algo más sencilla" no es lógica de negocio. Como no está claro el problema, no soluciona el problema. Y como no tienes datos, tampoco puedes trabajar con valores reales, rangos reales, o una mínima realidad que es lo que se busca en esta asignatura.
Cada vez que contestas a una pregunta introduces "problemas" nuevos y soluciones nuevas. Sigues sin poner un solo problema, y una sola lógica de negocio. Si se trata de no desperdiciar recursos, ¿qué lógica hay? ¿Recursos > x enviar mensaje? ¿Quieres repasar qué se considera una lógica de negocio aceptable, por favor?

2022-09-20 21:47 UTC, lovelace9981 commented
* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
Sí, es un problema que muchas empresas no conocen o suelen resolverlo de manera "manual". 
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue  de una aplicación en la nube?
Sí, la aplicación en la nube permite a la empresa de compra online descentralizar la lógica que permite automatizar las asignaciones de los productos devuelto a cada técnico especializado, proceso que se suele realizar manualmente.
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
Sí, hay una asignación de balanceo de carga al técnico especializado en el producto devuelto menos ocupado.
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?
Sí.

@JJ

2022-09-21 07:39 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
>       Sí, es un problema que muchas empresas no conocen o suelen resolverlo de manera "manual".
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue  de una aplicación en la nube?
>       Sí, la aplicación en la nube permite a la empresa de compra online descentralizar la lógica que permite automatizar las asignaciones de los productos devuelto a cada técnico especializado, proceso que se suele realizar manualmente.
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
>       Sí, hay una asignación de balanceo de carga al técnico especializado en el producto devuelto menos ocupado.
> 
>     * [x]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?
>       Sí.
> 
> 
> @JJ

Por favor, haz esta lista de comprobación en el cuerpo, no en los comentarios.

2022-09-21 07:44 UTC, JJ approved these changes
Voy a optar por aprobar, aunque no hay nada que impida que este proyecto sea una simple aplicación de escritorio, dado que todos los datos que hay son locales.
La lógica de negocio parece relativamente compleja, con lo que podría dar lugar a una validación interesante, y a probar diferentes estrategias de asignación. Voy a suponer también que tienes todos los datos para hacer pruebas con relativa seguridad (es decir, que tienes conocimiento personal de cómo va la carga de trabajo de este tipo de sitios o puedes generarlo de forma razonable).
Gracias por el esfuerzo, en todo caso.

2022-09-21 07:44 UTC, JJ commented on README.md
> +El proceso de asignación para comprobación de productos devueltos de una empresa de venta online, se hace de manera manual y sin tener en cuenta la carga de trabajo pendiente del técnico especializad
¿Tienes experiencia personal con este tipo de problemas? (ver pregunta 1)

2022-09-21 08:40 UTC, merged